dswebsite/dscience/urls.py
from django.conf.urls import patterns, url
from django.conf import settings

from dscience import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^presentation/$', views.presentation, name='presentation'),
    url(r'^presentation/latePUpload/$', views.latePUpload, name='latePUpload'),
    url(r'^assignment/$', views.assignment, name='assignment'),
    url(r'^myassignments/$', views.myassignments, name='myassignments'),
    url(r'^myassignments/(?P<asgn_id>\d+)/$', views.myassignmentdetail, name='myassignmentdetail'),
    url(r'^feedback/$', views.givefeedback, name='givefeedback'),
    url(r'^feedback/(?P<feed_id>\d+)/$', views.feedbackdetail, name='feedbackdetail'),
    url(r'^myfeedbacks/$', views.myfeedbacks, name='myfeedbacks'),
    # ex: /polls/5/
    url(r'^(?P<topic_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<topic_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<topic_id>\d+)/vote/$', views.vote, name='vote'),
    # Login / logout.
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
                        {'next_page': '../login/'}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                        'document_root': settings.MEDIA_ROOT,
    }),
                       
)

dswebsite/dswebsite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dswebsite.views.home', name='home'),
    # url(r'^dswebsite/', include('dswebsite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^dscience/', include('dscience.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

dswebsite/dscience/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    name = models.CharField(max_length=25)
    def __unicode__(self):
        return self.name

class Presentation(models.Model):
    topic = models.ForeignKey(Topic)
    first_due_date = models.DateTimeField('due date before meeting')
    upload_date = models.DateTimeField('presentation upload date')
    link = models.URLField(blank=True)
    pFile = models.FileField(upload_to='presentations', blank=True)
    def __unicode__(self):
        return self.topic.name

class Group(models.Model):
    name = models.CharField(max_length=25)
    presentation = models.ForeignKey(Presentation)
    def __unicode__(self):
        return self.name

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    group = models.ForeignKey(Group)
    def __unicode__(self):
        return self.user.username

class Assignment(models.Model):
    group = models.ForeignKey(Group)
    file = models.FileField(upload_to='assignments', blank=True)
    upload_due_date = models.DateTimeField('Assigned by admins')
    due_date = models.DateTimeField('due date of the assignment', blank=True, null=True)
    def __unicode__(self):
        return self.group.name

#Model to keep homeworks uploaded by users
class Homework(models.Model):
    assignment = models.ForeignKey(Assignment)
    user = models.ForeignKey(UserProfile) #Id of the user who uploads the hmw
    upload_date = models.DateTimeField('The date user made the upload')
    file = models.FileField(upload_to='homework')
    def __unicode__(self):
        return self.user.user.username

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/')

field_score_options = [(1,1),(2,2),(3,3),(4,4),(5,5)]

#Calculate deadline on the fly
class Feedback(models.Model):
    user_giving_feedback = models.ForeignKey(UserProfile,related_name='feedback_giving')
    user_getting_feedback = models.ForeignKey(UserProfile,related_name='feedback_getting')
    presentation = models.ForeignKey(Presentation)
    due_date = models.DateTimeField()
    date_given = models.DateTimeField()
    clarity = models.IntegerField(choices=field_score_options)
    exposition = models.IntegerField(choices=field_score_options)
    smoothness = models.IntegerField(choices=field_score_options)
    qa = models.IntegerField(choices=field_score_options)
    comments = models.TextField()
    is_given = models.BooleanField()
    def __unicode__(self):
        return self.user_giving_feedback.user.username
    



    

dswebsite/dscience/forms.py
from django import forms
from django.forms import ModelForm
from dscience.models import Feedback

class PresentationForm(forms.Form):
    presFile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
)

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

class AssignmentForm(forms.Form):
    assignfile = forms.FileField(
        label='Upload your assigment',
    )
    dueDate = forms.DateField( widget=forms.TextInput(attrs={'id':'id_form_date_field'}))

class MyAssignmentForm(forms.Form):
    myassignfile = forms.FileField(
                            label='Upload your assigment',
                 )

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ['clarity', 'exposition', 'smoothness', 'qa', 'comments']
        widgets = {'clarity' : forms.RadioSelect(), 'exposition' : forms.RadioSelect(), 'smoothness' : forms.RadioSelect(), 'qa' : forms.RadioSelect(), }

dswebsite/dscience/views.py
# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render, get_object_or_404, render_to_response
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from datetime import datetime
from django.utils import timezone

from dscience.models import Topic, Group, UserProfile, Assignment, Homework, Feedback
from dscience.forms import PresentationForm, DocumentForm, AssignmentForm, MyAssignmentForm, FeedbackForm

@login_required
def index(request):
    topic_list = Topic.objects.order_by("name")
    context = RequestContext(request, {
          'topic_list': topic_list,
    })
    return render(request, 'dscience/index.html', context)

@login_required
def presentation(request):
    #everything = Group.objects.all()
    uProfile = UserProfile.objects.select_related().get(user = request.user)

    if request.method == 'POST':
        form = PresentationForm(request.POST, request.FILES)
        first_due = uProfile.group.presentation.first_due_date;
        if form.is_valid():
            if first_due > timezone.now():
                print "late"
                uProfile.group.presentation.pFile = request.FILES['presFile']
                uProfile.group.presentation.save()
            
                # Redirect to the document list after POST
                return HttpResponseRedirect(reverse('dscience.views.presentation'))
            else:
                return HttpResponseRedirect(reverse('dscience.views.latePUpload'))
    else:
        form = PresentationForm() # A empty, unbound form

    # Load documents for the list page
    documents = uProfile.group.presentation.pFile;

    # Render list page with the documents and the form
    return render_to_response(
        'dscience/presentation.html',
        {'documents': documents, 'form': form, 'uProfile': uProfile},
        context_instance=RequestContext(request)
                              )

@login_required
def assignment(request):
    try:
        uProfile = UserProfile.objects.select_related().get(user = request.user)
    except UserProfile.DoesNotExist:
        uProfile = None

    try:
        assignInfo = Assignment.objects.get(group=uProfile.group)
    except Assignment.DoesNotExist:
        assignInfo = None

    context = RequestContext(request, {
                             'uProfile': uProfile,
                             'assignInfo': assignInfo,
                             })

    if request.method == 'POST' and not (assignInfo == None):
        form = AssignmentForm(request.POST, request.FILES)
        first_due = assignInfo.upload_due_date;
        if form.is_valid():
            if first_due > timezone.now():
                assignInfo.file = request.FILES['assignfile']
                assignInfo.due_date = request.POST['dueDate']
                assignInfo.save()
                return HttpResponseRedirect(reverse('dscience.views.assignment'))
            else:
                return HttpResponseRedirect(reverse('dscience.views.latePUpload'))

    elif assignInfo:
        form = AssignmentForm(initial={'dueDate': str(assignInfo.due_date).split(" ")[0]})
    else:
        form = AssignmentForm()
    return render_to_response('dscience/assignment.html', {'uProfile': uProfile, 'assignInfo': assignInfo, 'form': form }, context_instance=RequestContext(request))

@login_required
def myassignments(request):
    try:
        uProfile = UserProfile.objects.select_related().get(user = request.user)
    except UserProfile.DoesNotExist:
        uProfile = None
    
    try:
        myAssignInfo = Assignment.objects.exclude(group=uProfile.group)            
    except Assignment.DoesNotExist:
        myAssignInfo = None
    
    return render_to_response('dscience/myassignments.html', {'myAssignInfo': myAssignInfo }, context_instance=RequestContext(request))

@login_required
def myassignmentdetail(request, asgn_id):
    uProfile = UserProfile.objects.get(user=request.user)
    asgn = get_object_or_404(Assignment, pk=asgn_id)
    
    try:
        homew = Homework.objects.get(user=uProfile, assignment = asgn)
    except Homework.DoesNotExist:
        homew = None
    
    if request.method == 'POST' and not (asgn == None):
        form = MyAssignmentForm(request.POST, request.FILES)
        due = asgn.due_date;
        if form.is_valid():
            if due > timezone.now():
                now = datetime.now()
                
                if(homew):
                    print "update"
                    homew.upload_date = now
                    homew.file=request.FILES['myassignfile']
                    homew.save()
                else:
                    
                    hmw = Homework(assignment=asgn, user=uProfile, upload_date=now, file=request.FILES['myassignfile'])
                    hmw.save()
                return HttpResponseRedirect(reverse('dscience.views.myassignments'))
            else:
                return HttpResponseRedirect(reverse('dscience.views.latePUpload'))
    
    else:
        form = MyAssignmentForm()
    return render_to_response('dscience/asgndetail.html', {'asgn': asgn, 'form': form, 'homew': homew }, context_instance=RequestContext(request))

@login_required
def givefeedback(request):
    #everything = Group.objects.all()
    uProfile = UserProfile.objects.select_related().get(user = request.user)
    #Get all the feedbacks this user needs to give
    feedbackInfo = Feedback.objects.filter(user_giving_feedback = uProfile, is_given = 0)
    
    return render_to_response('dscience/givefeedback.html', {'uProfile' : uProfile, 'fInfo': feedbackInfo }, context_instance= RequestContext(request))

@login_required
def feedbackdetail(request, feed_id):
    uProfile = UserProfile.objects.get(user=request.user)
    feedback = get_object_or_404(Feedback, pk=feed_id)

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        due = feedback.due_date;
        if form.is_valid():
            if due > timezone.now():
                now = datetime.now()
                feedback.upload_date = now
                feedback.is_given = 1
                #Create form with post data
                f = FeedbackForm(request.POST, instance = feedback)
                f.save()
                messageText = 'Feedback for ' + str(feedback.user_getting_feedback) + ' for the presentation ' + str(feedback.presentation.topic.name) +' is given succesfully!'
                messages.success(request, messageText)
                return HttpResponseRedirect(reverse('dscience.views.givefeedback'))
            else:
                return HttpResponseRedirect(reverse('dscience.views.latePUpload'))
                    

    else:
        form = FeedbackForm()
    return render_to_response('dscience/feedbackdetail.html', {'uProfile': uProfile, 'feedback': feedback, 'form': form}, context_instance=RequestContext(request))


@login_required
def myfeedbacks(request):
    #everything = Group.objects.all()
    uProfile = UserProfile.objects.select_related().get(user = request.user)
    #Get all the feedbacks this user needs to give
    feedbacks = Feedback.objects.filter(user_getting_feedback = uProfile, is_given = 1)
    
    return render_to_response('dscience/myfeedbacks.html', {'uProfile' : uProfile, 'fInfo': feedbacks }, context_instance= RequestContext(request))

@login_required
def latePUpload(request):
    return render(request, 'dscience/lateUpload.html')

@login_required
def detail(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    return render(request, 'dscience/detail.html', {'topic': topic})

def results(request, poll_id):
    return HttpResponse("You're looking at the results of poll %s." % poll_id)

def vote(request, poll_id):
    return HttpResponse("You're voting on poll %s." % poll_id)

def logout_page(request):
    """
        Log users out and re-direct them to the main page.
        """
    logout(request)
    return HttpResponseRedirect('/login/')

dswebsite/dscience/templates/dscience/asgndetail.html
{% extends "base.html" %}

{% block head %}

<script>
    $(function() {
      $( "#id_form_date_field" ).datepicker({ dateFormat:
                                            'yy-mm-dd'});
      });
    
</script>

{% endblock %}

{% block body %}

<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <fieldset class="module aligned ">
            
            <div class="form-row field-topic">
                <div>
                    <label for="id_topic" class="required">Topic: </label>
                    <p id="id_topic" name="topic"> {{ asgn.group.presentation.topic }} </p>
                </div>
            </div>
            
            <div class="form-row">
                <div>
                    <label for="id_upload_due_date_0" class="required">Due Date:</label>
                    <h3 style="color:red;"> <b> <i> {{asgn.due_date}} </i> </b> </h3>
                </div>
            </div>
  
            <div class="form-row field-file">
                <div>
                    <label for="id_file">Assignment </label>
                    <a href="{{asgn.file.url}}"> View Assignment  </a>
                </div>
            </div>
            
            <div class="form-row field-file">
                {{ form.assignfile.errors }}
                <div>
                    <label for="id_file">Your submission:</label>
                    <br />
                    {% if homew %}
                        <a href="{{homew.file.url}}"> Previous submission  </a>
                    {% else %}
                        No submission yet.
                    {% endif %}
                        {{ form.myassignfile }}                    
                    </p>
                </div>
            </div>
            
        </fieldset>
        
        <div class="submit-row">
            <input type="submit" value="Save" class="default" name="_save" />
        </div>
        
    </div>
</form>

{% endblock %}

dswebsite/dscience/templates/dscience/assignment.html
{% extends "base.html" %}

{% block head %}

<script>
    $(function() {
      $( "#id_form_date_field" ).datepicker({ dateFormat:
                                            'yy-mm-dd'});
      });
    
</script>

{% endblock %}

{% block body %}

{% if assignInfo %}
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <fieldset class="module aligned ">
            
            <div class="form-row field-group">
                <div>
                    <label for="id_group" class="required">Group: </label>
                    <p id="id_group" name="group"> {{ uProfile.group.name }} </p>
                </div>
            </div>
            
            <div class="form-row">
                <div>
                    <label for="id_upload_due_date_0" class="required">Upload due:</label>
                    <h3 style="color:red;"> <b> <i> {{assignInfo.upload_due_date}} </i> </b> </h3>
                </div>
            </div>
            
            <div class="form-row field-file">
                {{ form.assignfile.errors }}
                {% if not assignInfo.file %}
                <div>
                    <label for="id_file">File:</label>You haven't uploaded any assignment yet.
                        <br />Add: {{ form.assignfile }}
                    
                    </p>
                </div>
                {% else %}
                <div>
                    <label for="id_file">File:</label>
                    <p class="file-upload"> Currently:
                    <a href="{{assignInfo.file.url}}"> {{ uProfile.group.name }} upload  </a>
                    <br />Change: {{ form.assignfile }}
                    
                    </p>
                </div>
                {% endif %}
            </div>
            
            <div class="form-row field-due_date">
                {{ form.dueDate.errors }}
                <div>
                    <label for="id_form_date_field">Due date:</label>
                    
                    <p class="datetime">
                    <p>

                    {{ form.dueDate }}
                    </p>
                    
                    </p>
                </div>
                
            </div>
            
        </fieldset>
        
        <div class="submit-row">
            <input type="submit" value="Save" class="default" name="_save" />
        </div>
        
    </div>
</form>

{% else %}

<div>
    <fieldset class="module aligned ">
        
        <div class="form-row field-group">
            <div>
                <p id="id_group" name="group"> You should present before you give your assignment. </p>
            </div>
        </div>
    </fieldset>
</div>

{% endif %}


{% endblock %}

dswebsite/dscience/templates/dscience/detail.html
{{ topic }}

dswebsite/dscience/templates/dscience/feedbackdetail.html
{% extends "base.html" %}

{% block head %}

<script>
    $(function() {
      $( "#id_form_date_field" ).datepicker({ dateFormat:
                                            'yy-mm-dd'});
      });
    
</script>

{% endblock %}

{% block body %}

<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <fieldset class="module aligned ">
            
            <div class="form-row field-topic">
                <div>
                    <label for="id_user" class="required">User: </label>
                    <p id="id_user" name="user"> {{ feedback.user_getting_feedback }} </p>
                </div>
            </div>
            
            <div class="form-row">
                <div>
                    <label for="id_upload_due_date_0" class="required">Due Date:</label>
                    <h3 style="color:red;"> <b> <i> {{feedback.due_date}} </i> </b> </h3>
                </div>
            </div>
  
            <div class="form-row field-file">
                <div>
                    <label for="id_topic">Presentation </label>
                    <p id="id_topic" name="topic"> {{ feedback.presentation.topic.name }} </p>
                </div>
            </div>
            
            <div class="form-row field-clarity">
                {{ form.clarity.errors }}
                <div>
                    <label for="id_file">Clarity:</label>
                    <br />
                    {% for radio in form.clarity %}
                    {% if not forloop.first %}
                    <div class="myradio">
                        {{ radio }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    </p>
                </div>
                
            </div>

            <div class="form-row field-exposition">
                {{ form.exposition.errors }}
                <div>
                    <label for="id_file">Exposition:</label>
                    <br />
                    {% for radio in form.exposition %}
                    {% if not forloop.first %}
                    <div class="myradio">
                        {{ radio }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    </p>
                </div>
                
            </div>
            
            <div class="form-row field-smoothness">
                {{ form.smoothness.errors }}
                <div>
                    <label for="id_file">Smoothness:</label>
                    <br />
                    {% for radio in form.smoothness %}
                    {% if not forloop.first %}
                    <div class="myradio">
                        {{ radio }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    </p>
                </div>
                
            </div>

            <div class="form-row field-qa">
                {{ form.qa.errors }}
                <div>
                    <label for="id_file">Q-A:</label>
                    <br />
                    {% for radio in form.qa %}
                    {% if not forloop.first %}
                    <div class="myradio">
                        {{ radio }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    </p>
                </div>
                
            </div>
            
            <div class="form-row field-file">
                {{ form.comments.errors }}
                <div>
                    <label for="id_comment">Comments </label>
                    <p id="id_comment" name="comment"> {{ form.comments }} </p>
                </div>
            </div>
            
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="Save" class="default" name="_save" />
        </div>
        
    </div>
</form>

{% endblock %}

dswebsite/dscience/templates/dscience/givefeedback.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css" />
{% endblock %}

{% block body %}

<!-- Content -->
<div id="content" class="colMS">
    
    <div id="content-main">
        <div class="module">
            <table>
                <caption>
                    <a href="/dscience/feedback/" class="section" title="Homeworks">
                        Feedbacks Waiting
                    </a>
                </caption>
                {% if fInfo %}
                {% for feedback in fInfo %}
                <tr>
                    <th scope="row"> <a href="/dscience/feedback/{{feedback.id}}"> {{feedback.user_getting_feedback}} </a></th>
                    <td> DUE : {{feedback.due_date}} </td>
                    
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <th scope="row"> You don't need to give any feedbacks now. </th>
                </tr>
                {% endif %}
                
            </table>
        </div>
    </div>
    
</div>
{% endblock %}

dswebsite/dscience/templates/dscience/index.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css" />
{% endblock %}

{% block body %}

<!-- Content -->
<div id="content" class="colMS">
    <div id="content-main">
        <div>
            <table>
                <tr>
                    <th scope="row"> <a href="/dscience/assignment/">Give assignment</a> </th>
                    
                </tr>
                <tr>
                    <th scope="row"> <a href="/dscience/presentation/">Presentation details</a> </th>
                    
                </tr>
                <tr>
                    <th scope="row"> <a href="/dscience/myassignments/">My Assignments</a> </th>
                    
                </tr>
                <tr>
                    <th scope="row"> <a href="/dscience/feedback/">Give Feedback</a> </th>
                    
                </tr>
                <tr>
                    <th scope="row"> <a href="/dscience/myfeedbacks/">My Feedbacks</a> </th>
                    
                </tr>
                <tr>
                    <th scope="row"> <a href="/dscience/logout">logout</a> </th>
                    
                </tr>
            </table>
        </div>
    </div>
    
</div>
{% endblock %}

dswebsite/dscience/templates/dscience/lateUpload.html
lateUploadMen!

dswebsite/dscience/templates/dscience/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>   
    </head>
    <body>
    <!-- List of uploaded documents -->
    {% if documents %}
        <ul>
        {% for document in documents %}
            <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form>
    </body>
</html> 

dswebsite/dscience/templates/dscience/myassignments.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css" />
{% endblock %}

{% block body %}

<!-- Content -->
<div id="content" class="colMS">
    
<div id="content-main">
    <div class="module">
        <table>
            <caption>
                <a href="/dscience/myassignments/" class="section" title="Homeworks">
                    My Assignments
                </a>
            </caption>
            {% if myAssignInfo %}
            {% for assign in myAssignInfo %}
                <tr>
                    <th scope="row"> <a href="/dscience/myassignments/{{assign.id}}"> {{assign.group.presentation.topic}} </a></th>
                    <td> DUE : {{assign.due_date}} </td>
                    
                </tr>
            {% endfor %}
            {% else %}
                <tr>
                    <th scope="row"> You don't have any homeworks </th>
                </tr>
            {% endif %}
            
        </table>
    </div>
</div>
    
</div>
{% endblock %}

dswebsite/dscience/templates/dscience/myfeedbacks.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css" />
{% endblock %}

{% block body %}

{% for feedback in fInfo %}

<!-- Content -->
<div id="content" class="colMS">
    
    <div id="content-main">
        <div class="module">
            <table>
                <caption>
                    <a href="/dscience/feedback/" class="section" title="Homeworks">
                        Feedback {{forloop.counter}}
                    </a>
                </caption>
                
                <tr>
                    <th scope="row"> Presentation </th>
                    <td> {{feedback.presentation.topic.name}} </td>
                    
                </tr>
                
                <tr>
                    <th scope="row"> Clarity </th>
                    <td> {{feedback.clarity}} </td>
                </tr>

                <tr>
                    <th scope="row"> Exposition </th>
                    <td> {{feedback.exposition}} </td>
                </tr>
                
                <tr>
                    <th scope="row">  Smoothness </th>
                    <td> {{feedback.smoothness}} </td>
                </tr>
                
                <tr>
                    <th scope="row">  Q-A </th>
                    <td> {{feedback.qa}} </td>
                </tr>

                <tr>
                    <th scope="row">  Comments </th>
                    <td> {{feedback.comments}} </td>
                </tr>
                
            </table>
        </div>
    </div>
    
</div>

{% endfor %}

{% endblock %}

dswebsite/dscience/templates/dscience/presentation.html
{% extends "base.html" %}

{% block head %}

<script>
    $(function() {
      $( "#id_form_date_field" ).datepicker({ dateFormat:
                                            'yy-mm-dd'});
      });
    
    </script>

{% endblock %}

{% block body %}

<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <fieldset class="module aligned ">
            
            <div class="form-row field-group">
                <div>
                    <label for="id_group" class="required">Group: </label>
                    <p id="id_group" name="group"> {{ uProfile.group.name }} </p>
                </div>
            </div>
            
            <div class="form-row">
                <div>
                    <label for="id_first_upload_due_date_0" class="required">First Upload due (meeting):</label>
                    <h3 style="color:red;"> <b> <i> {{ uProfile.group.presentation.first_due_date }} </i> </b> </h3>
                </div>
            </div>
            
            <div class="form-row">
                <div>
                    <label for="id_upload_due_date_0" class="required">Upload due:</label>
                    <h3 style="color:red;"> <b> <i> {{uProfile.group.presentation.upload_date}} </i> </b> </h3>
                </div>
            </div>
            
            <div class="form-row field-file">
                {{ form.presFile.errors }}
                {% if not documents %}
                <div>
                    <label for="id_file">File:</label>You haven't uploaded your presentation yet.
                    <br />Add: {{ form.presFile }}
                    
                    </p>
                </div>
                {% else %}
                <div>
                    <label for="id_file">File:</label>
                    <p class="file-upload"> Currently:
                    <a href="{{uProfile.group.presentation.pFile.url}}"> {{ uProfile.group.name }} upload  </a>
                    <br />Change: {{ form.presFile }}
                    
                    </p>
                </div>
                {% endif %}
            </div>
            
        </fieldset>
        
        <div class="submit-row">
            <input type="submit" value="Save" class="default" name="_save" />
        </div>
        
    </div>
</form>

{% endblock %}